"""initial schema

Revision ID: fd133a1dd93d
Revises: 
Create Date: 2026-09-01 00:35:49.791522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd133a1dd93d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='gender'), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_riders_phone_number'), 'riders', ['phone_number'], unique=True)
    op.create_table('ride_intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rider_id', sa.Uuid(), nullable=False),
    sa.Column('origin_station', sa.String(length=200), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('luggage_size', sa.Enum('NONE', 'SMALL', 'MEDIUM', 'LARGE', name='luggagesize'), nullable=False),
    sa.Column('gender_preference', sa.Enum('ANY', 'MALE', 'FEMALE', name='genderpreference'), nullable=False),
    sa.Column('expected_arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matching_window_opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matching_window_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MATCHED', 'EXPIRED', 'CANCELLED', name='intentstatus'), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], use_alter=True),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_intents_rider_id'), 'ride_intents', ['rider_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intent_a_id', sa.Uuid(), nullable=False),
    sa.Column('intent_b_id', sa.Uuid(), nullable=False),
    sa.Column('combined_stop_order', sa.JSON(), nullable=False),
    sa.Column('fare_split', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='matchstatus'), nullable=False),
    sa.Column('rider_a_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rider_b_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intent_a_id'], ['ride_intents.id'], ),
    sa.ForeignKeyConstraint(['intent_b_id'], ['ride_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('stop_order', sa.JSON(), nullable=False),
    sa.Column('fare_split', sa.JSON(), nullable=False),
    sa.Column('booking_provider', sa.Enum('MANUAL_CONFIRMATION', name='bookingprovidername'), nullable=False),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('READY', 'BOOKED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='ridestatus'), nullable=False),
    sa.Column('cancellation_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_match_id'), 'rides', ['match_id'], unique=True)

def downgrade() -> None:
    op.drop_index(op.f('ix_rides_match_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_table('matches')
    op.drop_index(op.f('ix_ride_intents_rider_id'), table_name='ride_intents')
    op.drop_table('ride_intents')
    op.drop_index(op.f('ix_riders_phone_number'), table_name='riders')
    op.drop_table('riders')
